/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as LaFirmaRouteImport } from './routes/la-firma'
import { Route as RutaDeInversionRouteImport } from './routes/ruta-de-inversion'
import { Route as ServiciosComplementariosRouteImport } from './routes/servicios-complementarios'
import { Route as AreasDePracticaIndexRouteImport } from './routes/areas-de-practica.index'
import { Route as AreasDePracticaAreaRouteImport } from './routes/areas-de-practica.$area'
import { Route as MercadosDiasporaDominicanaRouteImport } from './routes/mercados.diaspora-dominicana'
import { Route as MercadosInversionistasColombiaRouteImport } from './routes/mercados.inversionistas-colombia'
import { Route as RecursosIndexRouteImport } from './routes/recursos.index'
import { Route as RecursosReformaCodigoTrabajoRouteImport } from './routes/recursos.reforma-codigo-trabajo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const LaFirmaRoute = LaFirmaRouteImport.update({
  id: '/la-firma',
  path: '/la-firma',
  getParentRoute: () => rootRouteImport,
} as any)
const RutaDeInversionRoute = RutaDeInversionRouteImport.update({
  id: '/ruta-de-inversion',
  path: '/ruta-de-inversion',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosComplementariosRoute =
  ServiciosComplementariosRouteImport.update({
    id: '/servicios-complementarios',
    path: '/servicios-complementarios',
    getParentRoute: () => rootRouteImport,
  } as any)
const AreasDePracticaIndexRoute = AreasDePracticaIndexRouteImport.update({
  id: '/areas-de-practica/',
  path: '/areas-de-practica/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasDePracticaAreaRoute = AreasDePracticaAreaRouteImport.update({
  id: '/areas-de-practica/$area',
  path: '/areas-de-practica/$area',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadosDiasporaDominicanaRoute =
  MercadosDiasporaDominicanaRouteImport.update({
    id: '/mercados/diaspora-dominicana',
    path: '/mercados/diaspora-dominicana',
    getParentRoute: () => rootRouteImport,
  } as any)
const MercadosInversionistasColombiaRoute =
  MercadosInversionistasColombiaRouteImport.update({
    id: '/mercados/inversionistas-colombia',
    path: '/mercados/inversionistas-colombia',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecursosIndexRoute = RecursosIndexRouteImport.update({
  id: '/recursos/',
  path: '/recursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosReformaCodigoTrabajoRoute =
  RecursosReformaCodigoTrabajoRouteImport.update({
    id: '/recursos/reforma-codigo-trabajo',
    path: '/recursos/reforma-codigo-trabajo',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/la-firma': typeof LaFirmaRoute
  '/ruta-de-inversion': typeof RutaDeInversionRoute
  '/servicios-complementarios': typeof ServiciosComplementariosRoute
  '/areas-de-practica/$area': typeof AreasDePracticaAreaRoute
  '/mercados/diaspora-dominicana': typeof MercadosDiasporaDominicanaRoute
  '/mercados/inversionistas-colombia': typeof MercadosInversionistasColombiaRoute
  '/recursos/reforma-codigo-trabajo': typeof RecursosReformaCodigoTrabajoRoute
  '/areas-de-practica/': typeof AreasDePracticaIndexRoute
  '/recursos/': typeof RecursosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/la-firma': typeof LaFirmaRoute
  '/ruta-de-inversion': typeof RutaDeInversionRoute
  '/servicios-complementarios': typeof ServiciosComplementariosRoute
  '/areas-de-practica/$area': typeof AreasDePracticaAreaRoute
  '/mercados/diaspora-dominicana': typeof MercadosDiasporaDominicanaRoute
  '/mercados/inversionistas-colombia': typeof MercadosInversionistasColombiaRoute
  '/recursos/reforma-codigo-trabajo': typeof RecursosReformaCodigoTrabajoRoute
  '/areas-de-practica': typeof AreasDePracticaIndexRoute
  '/recursos': typeof RecursosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/la-firma': typeof LaFirmaRoute
  '/ruta-de-inversion': typeof RutaDeInversionRoute
  '/servicios-complementarios': typeof ServiciosComplementariosRoute
  '/areas-de-practica/$area': typeof AreasDePracticaAreaRoute
  '/mercados/diaspora-dominicana': typeof MercadosDiasporaDominicanaRoute
  '/mercados/inversionistas-colombia': typeof MercadosInversionistasColombiaRoute
  '/recursos/reforma-codigo-trabajo': typeof RecursosReformaCodigoTrabajoRoute
  '/areas-de-practica/': typeof AreasDePracticaIndexRoute
  '/recursos/': typeof RecursosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/la-firma'
    | '/ruta-de-inversion'
    | '/servicios-complementarios'
    | '/areas-de-practica/$area'
    | '/mercados/diaspora-dominicana'
    | '/mercados/inversionistas-colombia'
    | '/recursos/reforma-codigo-trabajo'
    | '/areas-de-practica/'
    | '/recursos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/la-firma'
    | '/ruta-de-inversion'
    | '/servicios-complementarios'
    | '/areas-de-practica/$area'
    | '/mercados/diaspora-dominicana'
    | '/mercados/inversionistas-colombia'
    | '/recursos/reforma-codigo-trabajo'
    | '/areas-de-practica'
    | '/recursos'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/la-firma'
    | '/ruta-de-inversion'
    | '/servicios-complementarios'
    | '/areas-de-practica/$area'
    | '/mercados/diaspora-dominicana'
    | '/mercados/inversionistas-colombia'
    | '/recursos/reforma-codigo-trabajo'
    | '/areas-de-practica/'
    | '/recursos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  LaFirmaRoute: typeof LaFirmaRoute
  RutaDeInversionRoute: typeof RutaDeInversionRoute
  ServiciosComplementariosRoute: typeof ServiciosComplementariosRoute
  AreasDePracticaAreaRoute: typeof AreasDePracticaAreaRoute
  MercadosDiasporaDominicanaRoute: typeof MercadosDiasporaDominicanaRoute
  MercadosInversionistasColombiaRoute: typeof MercadosInversionistasColombiaRoute
  RecursosReformaCodigoTrabajoRoute: typeof RecursosReformaCodigoTrabajoRoute
  AreasDePracticaIndexRoute: typeof AreasDePracticaIndexRoute
  RecursosIndexRoute: typeof RecursosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-firma': {
      id: '/la-firma'
      path: '/la-firma'
      fullPath: '/la-firma'
      preLoaderRoute: typeof LaFirmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruta-de-inversion': {
      id: '/ruta-de-inversion'
      path: '/ruta-de-inversion'
      fullPath: '/ruta-de-inversion'
      preLoaderRoute: typeof RutaDeInversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios-complementarios': {
      id: '/servicios-complementarios'
      path: '/servicios-complementarios'
      fullPath: '/servicios-complementarios'
      preLoaderRoute: typeof ServiciosComplementariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-de-practica/': {
      id: '/areas-de-practica/'
      path: '/areas-de-practica'
      fullPath: '/areas-de-practica/'
      preLoaderRoute: typeof AreasDePracticaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-de-practica/$area': {
      id: '/areas-de-practica/$area'
      path: '/areas-de-practica/$area'
      fullPath: '/areas-de-practica/$area'
      preLoaderRoute: typeof AreasDePracticaAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercados/diaspora-dominicana': {
      id: '/mercados/diaspora-dominicana'
      path: '/mercados/diaspora-dominicana'
      fullPath: '/mercados/diaspora-dominicana'
      preLoaderRoute: typeof MercadosDiasporaDominicanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercados/inversionistas-colombia': {
      id: '/mercados/inversionistas-colombia'
      path: '/mercados/inversionistas-colombia'
      fullPath: '/mercados/inversionistas-colombia'
      preLoaderRoute: typeof MercadosInversionistasColombiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/': {
      id: '/recursos/'
      path: '/recursos'
      fullPath: '/recursos/'
      preLoaderRoute: typeof RecursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/reforma-codigo-trabajo': {
      id: '/recursos/reforma-codigo-trabajo'
      path: '/recursos/reforma-codigo-trabajo'
      fullPath: '/recursos/reforma-codigo-trabajo'
      preLoaderRoute: typeof RecursosReformaCodigoTrabajoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  LaFirmaRoute: LaFirmaRoute,
  RutaDeInversionRoute: RutaDeInversionRoute,
  ServiciosComplementariosRoute: ServiciosComplementariosRoute,
  AreasDePracticaAreaRoute: AreasDePracticaAreaRoute,
  MercadosDiasporaDominicanaRoute: MercadosDiasporaDominicanaRoute,
  MercadosInversionistasColombiaRoute: MercadosInversionistasColombiaRoute,
  RecursosReformaCodigoTrabajoRoute: RecursosReformaCodigoTrabajoRoute,
  AreasDePracticaIndexRoute: AreasDePracticaIndexRoute,
  RecursosIndexRoute: RecursosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
